# Generated by Django 5.2.5 on 2025-08-12 05:08

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(blank=True, choices=[('b', 'Select Material'), ('b', 'Batteries'), ('c', 'Cement'), ('cw', 'Cables & Wires'), ('ep', 'Electrical Panels'), ('gc', 'Gravel & Crush'), ('p', 'Paints'), ('pf', 'Pipes & Fittings'), ('s', 'Steel'), ('sp', 'Solar Panels')], default='b', help_text='Select selling material.', max_length=2)),
                ('brand', models.CharField(max_length=200)),
                ('purchase_price', models.FloatField(blank=True, null=True)),
                ('selling_price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['material'],
            },
        ),
        migrations.CreateModel(
            name='Sellor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_store_name', models.CharField(max_length=200)),
                ('owner', models.CharField(max_length=200, verbose_name='Owner Name / مالک کا نام')),
                ('address_1', models.CharField(max_length=200)),
                ('address_2', models.CharField(max_length=200)),
                ('tehsil', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('mohalla', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('network', models.CharField(max_length=200)),
                ('cell', models.CharField(max_length=200)),
                ('material', models.ForeignKey(help_text='Select Material you carry.', null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.material')),
            ],
            options={
                'ordering': ['registered_store_name'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('registered_store_name'), name='registered_store_name_case_insensitive_unique', violation_error_message='Registered Store Name already exists (case insensitive match)')],
            },
        ),
    ]
