# Generated by Django 5.2.5 on 2025-08-16 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categories - زمرہ جات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='catalog.category')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'category')},
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.brand')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.store')),
            ],
            options={
                'unique_together': {('name', 'brand', 'store')},
            },
        ),
        migrations.CreateModel(
            name='ConcreteAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=50)),
                ('slump_mm', models.PositiveIntegerField()),
                ('aggregate_size_mm', models.PositiveIntegerField()),
                ('cement_ratio', models.CharField(max_length=50)),
                ('item', models.OneToOneField(limit_choices_to={'brand__category__name': 'Concrete'}, on_delete=django.db.models.deletion.CASCADE, to='catalog.item')),
            ],
        ),
        migrations.CreateModel(
            name='CementAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=50)),
                ('weight_per_bag_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('setting_time_min', models.PositiveIntegerField()),
                ('compressive_strength_mpa', models.DecimalField(decimal_places=2, max_digits=5)),
                ('item', models.OneToOneField(limit_choices_to={'brand__category__name': 'Cement'}, on_delete=django.db.models.deletion.CASCADE, to='catalog.item')),
            ],
        ),
        migrations.CreateModel(
            name='CableAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cable_type', models.CharField(max_length=50)),
                ('conductor_material', models.CharField(max_length=50)),
                ('cross_section_area_mm2', models.DecimalField(decimal_places=2, max_digits=6)),
                ('voltage_rating_v', models.PositiveIntegerField()),
                ('insulation_type', models.CharField(max_length=50)),
                ('item', models.OneToOneField(limit_choices_to={'brand__category__name': 'Cables'}, on_delete=django.db.models.deletion.CASCADE, to='catalog.item')),
            ],
        ),
        migrations.CreateModel(
            name='BrickAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brick_type', models.CharField(max_length=50)),
                ('dimensions_mm', models.CharField(max_length=50)),
                ('compressive_strength_mpa', models.DecimalField(decimal_places=2, max_digits=6)),
                ('water_absorption_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('item', models.OneToOneField(limit_choices_to={'brand__category__name': 'Bricks'}, on_delete=django.db.models.deletion.CASCADE, to='catalog.item')),
            ],
        ),
        migrations.CreateModel(
            name='PaintAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paint_type', models.CharField(max_length=50)),
                ('base', models.CharField(max_length=50)),
                ('coverage_per_liter_sqm', models.DecimalField(decimal_places=2, max_digits=6)),
                ('drying_time_hours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('item', models.OneToOneField(limit_choices_to={'brand__category__name': 'Paint'}, on_delete=django.db.models.deletion.CASCADE, to='catalog.item')),
            ],
        ),
        migrations.CreateModel(
            name='PipeAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipe_material', models.CharField(max_length=50)),
                ('nominal_diameter', models.DecimalField(decimal_places=2, max_digits=6)),
                ('diameter_unit', models.CharField(default='mm', max_length=10)),
                ('length_m', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pressure_rating', models.CharField(max_length=50)),
                ('item', models.OneToOneField(limit_choices_to={'brand__category__name': 'Pipes'}, on_delete=django.db.models.deletion.CASCADE, to='catalog.item')),
            ],
        ),
        migrations.CreateModel(
            name='SandAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sand_type', models.CharField(max_length=50)),
                ('grain_size_mm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('source_location', models.CharField(max_length=100)),
                ('item', models.OneToOneField(limit_choices_to={'brand__category__name': 'Sand'}, on_delete=django.db.models.deletion.CASCADE, to='catalog.item')),
            ],
        ),
        migrations.CreateModel(
            name='SteelAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steel_type', models.CharField(max_length=50)),
                ('diameter_mm', models.PositiveIntegerField()),
                ('tensile_strength_mpa', models.PositiveIntegerField()),
                ('item', models.OneToOneField(limit_choices_to={'brand__category__name': 'Steel'}, on_delete=django.db.models.deletion.CASCADE, to='catalog.item')),
            ],
        ),
        migrations.CreateModel(
            name='StoreItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reorder_point', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sku', models.CharField(blank=True, max_length=50, null=True)),
                ('barcode', models.CharField(blank=True, max_length=50, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.item')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.store')),
            ],
            options={
                'unique_together': {('store', 'item')},
            },
        ),
    ]
