# Generated by Django 5.2.5 on 2025-08-12 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_sellor_address_1_alter_sellor_address_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='material',
            field=models.CharField(blank=True, choices=[('b', 'Select Material'), ('Batteries', 'Batteries'), ('Cement', 'Cement'), ('Cables & Wires', 'Cables & Wires'), ('Electrical Panels', 'Electrical Panels'), ('Gravel & Crush', 'Gravel & Crush'), ('Paints', 'Paints'), ('Pipes & Fittings', 'Pipes & Fittings'), ('Steel', 'Steel'), ('Solar Panels', 'Solar Panels')], default='b', help_text='Select material from list.', max_length=20),
        ),
    ]
