# Generated by Django 5.2.5 on 2025-08-12 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_material_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_category', models.CharField(blank=True, choices=[('b', 'Select Material'), ('Batteries', 'Batteries'), ('Cement', 'Cement'), ('Cables & Wires', 'Cables & Wires'), ('Electrical Panels', 'Electrical Panels'), ('Gravel & Crush', 'Gravel & Crush'), ('Paints', 'Paints'), ('Pipes & Fittings', 'Pipes & Fittings'), ('Steel', 'Steel'), ('Solar Panels', 'Solar Panels')], default='b', help_text='Select material from list.', max_length=20)),
                ('brand', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['material_category'],
            },
        ),
        migrations.AlterField(
            model_name='sellor',
            name='material',
            field=models.ForeignKey(help_text='Select Material you carry.', null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.materialcategory'),
        ),
        migrations.DeleteModel(
            name='Material',
        ),
    ]
