# Generated by Django 5.2.5 on 2025-08-17 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_category_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='category',
            name='category_name_case_insensitive_unique',
        ),
    ]
