# Generated by Django 5.2.5 on 2025-08-17 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_category_category_name_case_insensitive_unique'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='brand',
            name='brand_name_case_insensitive_unique',
        ),
        migrations.RemoveConstraint(
            model_name='item',
            name='item_name_case_insensitive_unique',
        ),
        migrations.AlterUniqueTogether(
            name='brand',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together=set(),
        ),
    ]
