# Generated by Django 5.2.5 on 2025-08-17 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_brand_options_alter_item_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='store',
            name='store_name_case_insensitive_unique',
        ),
    ]
